### ISSUE TITLE
Icon request: Icons for API Manager

### ISSUE THREAD

**Issue by vlgunarathne** [wso2-attic/ux-font-wso2#102]
fw-angular
fw-babel
fw-backbone
fw-bitbucket
fw-c
fw-cakephp
fw-ceylon
fw-chrome
fw-coffeescript
fw-confluence
fw-couchdb
fw-cplusplus
fw-csharp
fw-css3
fw-django
fw-docker
fw-dotnet
fw-firefox
fw-git
fw-go
fw-heroku
fw-html5
fw-intellij
fw-ionic
fw-javascript
fw-jetbrains
fw-meteor
fw-mongodb
fw-mysql
fw-nginx
fw-nodewebkit
fw-oracle
fw-phpstorm
fw-postgresql
fw-pycharm
fw-python
fw-rails
fw-react
fw-redhat
fw-ruby
fw-safari
fw-swift
fw-tomcat
fw-typescript
fw-vagrant
fw-vim
fw-webpack
fw-webstorm
fw-wordpress
fw-yarn

**Comment by dakshika** [comment]
Why APIM need these icons? please clarify?

**Comment by vlgunarathne** [comment]
API Manager supports SDK generation for the published APIs and the UI component of that feature will be a set of tiles depicting the specific programming language icon along with a download button so that the user will be able to easily identify which SDK to download to match his/her requirements.

**Comment by dakshika** [comment]
AFAIK we are not supported for all above-listed things. please list down current language list that we are going to support
