### ISSUE TITLE
Icon request: icons for Analytics Dashboard 

### ISSUE THREAD

**Issue by srsharon** [wso2-attic/ux-font-wso2#77]
fw-aggregate-mediator
fw-bam-mediator
fw-bean-mediator
fw-cache-mediator
fw-call-template-mediator
fw-callout-mediator
fw-class-mediator
fw-clone
fw-conditional-router-mediator
fw-db-lookup-mediator
fw-db-report-mediator
fw-drop-mediator
fw-ejb-mediator
fw-enqueue-mediator
fw-enrich-mediator
fw-entitlement-mediator
fw-event-mediator
fw-fast-xslt-mediator
fw-fault-mediator
fw-foreach
fw-iterate-mediator
fw-loop-back
fw-oauth-mediator
fw-pojo-command-mediator
fw-rule-mediator
fw-script-mediator
fw-send-mediators
fw-smooks-mediator
fw-spring-mediator
fw-store-mediator
fw-switch-mediator
fw-throttle-mediator
fw-transaction-mediator
fw-url-rewrite-mediator
fw-validate-mediator
fw-xquery-mediator
fw-xslt-mediator

**Comment by jeradrutnam** [comment]
@srsharon as discussed please make these icon generic and take out the "mediator" term.
